train_batch_size: 64
test_batch_size: 64
learning_rate: 0.0005
log_interval: 20
num_epochs: 5
lambda_l2: 0.001
size1: 128
size2: 1024
size3: 128
size4: 128
size5: 128
size6: 128
size7: 128
layers: 1
num: 2